# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: /:title/

# Setup
title: Slightly Innovative
description: What works at work works because it works not because its work.
tagline: Better is still better
url: http://slightlyinnovative.com
paginate: 5

# Custom vars
disqus_short_name: slightly-innovative
version: 1.0.0
github:
  repo: https://github.com/slightly-innovative/slightly-innovative.github.io

baseurl: ""
encoding: utf-8
