# Site settings
title: Slightly Innovative
email: not_setup_yet@slightlyinnovative.com
description: "A co-authored blog by Josh Carlson and Jason Carr"
baseurl: ""
url: "http://slightlyinnovative.com"

# Build settings
markdown: kramdown
permalink: pretty
