# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: /blog/:title/

# Setup
title: "PerByte: Slightly Innovative"
description: What works at work works because it works not because it's work.
tagline: Better is still better
url: http://www.perbyte.com
paginate: 5
paginate_path: "blog/page:num"

# Custom vars
disqus_short_name: slightlyinnovative
version: 1.0.0
github:
  repo: https://github.com/sperbyte/perbyte.github.io

baseurl: ""
encoding: utf-8

gems:
    - jemoji
